name: keep_it
description: An all allows you to preserve the images you get from web in an organized manner, without messing it up with photos.
publish_to: 'none' 
homepage: htts://www.cloudonlanapps.com

version: 0.1.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/nature-sky-water-sea-natural-landscape-ocean-1520813-pxhere.com.jpg
